### ISSUE TITLE
Pasting issue in Firefox

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/redactor#103]
Have a strange issue exclusively in Firefox; when pasting content from other redactor fields line length is capped by `<br>`'s being inserted to the content.

I whipped up a quick screen recording which hopefully does a far better job of explaining here:
https://youtu.be/9YgHVyyhsVA

Here are some shots of the redactor markup too:
<img width="2032" alt="Redactor Copy Source" src="https://user-images.githubusercontent.com/12031196/49157599-17459180-f318-11e8-88af-8443f0269b74.png">
<img width="2032" alt="Redactor After Paste" src="https://user-images.githubusercontent.com/12031196/49157600-17459180-f318-11e8-8f25-c989f3887c9c.png">

Finally, we tried installing the latest dev branch version of the plugin (which includes Redactor `3.1.4`) but the issue remained.

We're running the latest version of Craft on PHP 7.1.19 and Postgres 9.5.14

**Comment by andris-sevcenko** [comment]
Can you reproduce that on the https://imperavi.com/redactor/ page? That one currently is at Redactor 3.1.5.

**Comment by alexjcollins** [comment]
@andris-sevcenko No we can't and after a bit more messing around, we've noticed this only happens when you pass `"pastePlainText": true` in the redactor config.

**Comment by andris-sevcenko** [comment]
This is _probably_ fixed in Redactor 3.1.6. 

I'll try to get a release out the door today so you can test that.

**Comment by andris-sevcenko** [comment]
Is this still an issue?

**Comment by andris-sevcenko** [comment]
This is *probably* fixed with the release of 2.3.2 of this plugin. Let me know if it's not.

**Comment by jlcharette** [comment]
This is still happening in Craft 3.4.30 using Redactor v2.6.1. I was able to reproduce the behavior on impravi redactor demo page.

One thing I noticed is that the formatting is messed up when copy pasting text from a <div>. If you copy paste from a <p> tag, the output is fine.

**Comment by andris-sevcenko** [comment]
> I was able to reproduce the behavior on impravi redactor demo page.

yeah, that means that the bug is on their end and there's not much we can do about it. Once they fix it, we can bump the Redactor version we're using.
