### ISSUE TITLE
adding second link in lists overrides first listitem

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/redactor#104]
Something goes wrong when we try to add a second link in a list. See our video to reproduce the bug.

[redactor-links-lists-bug.mov](https://drive.google.com/file/d/1s-fDMZ6UQqMTzuHTlvOHd5j75UqSHn-s/view?usp=sharing)

craftcms/cms 3.0.33
craftcms/redactor 2.1.6

**Comment by alandowling** [comment]
I'm having this same issue. It seems to happen anytime there are items one after another (not just limited to lists). Also happens with paragraphs. If the first item is a link and the second is just text and that text is selected and turned into a link then the first link is overridden (both link and text). This issue doesn't appear to happen if the previous item is not a link.

see: [example of issue](https://www.dropbox.com/s/k1xia2n5oxx3u1p/Screen%20Recording%202018-12-06%20at%2010.06.33%20AM.mov?dl=0)

craftcms/cms 3.0.34
craftcms/redactor 2.1.6

**Comment by chadspencer** [comment]
I'm seeing this issue as well. I think the Craft Redactor plugin is a couple versions behind the Redactor. I'm wondering if that will solve the issue.

**Comment by andris-sevcenko** [comment]
Yeah, it's fixed by updating the Redactor version, but for some reason, I forgot to release that. Gonna make a release with just that now.

**Comment by andris-sevcenko** [comment]
And done. https://github.com/craftcms/redactor/releases/tag/2.1.7

**Comment by carolineboeykens** [comment]
I'm now running on Redactor 2.1.7, but the bug is still there.

**Comment by carolineboeykens** [comment]
"3.1.4"

**Comment by rickbergmans** [comment]
I'm experiencing the same issue when I'm trying to add a link to text in a table cell. Redactor fixed this issue in v3.1.5, so please update Redactor in the next plugin version.

**Comment by andris-sevcenko** [comment]
Fixed via 366dfd1

**Comment by carolineboeykens** [comment]
I updated Craft to 3.1.5 and Redactor to 2.3.0, I cleared cache, deleted the cpresources folder but the bug is still there. If I type `$R.version` in the console the result is 3.1.6. Am I doing something wrong?

**Comment by andris-sevcenko** [comment]
I am not able to reproduce this, unfortunately. Is it possible to get CP access to a site where you can reproduce this? If so, can you send it over to support@craftcms.com and reference this ticket?

**Comment by alandowling** [comment]
Has this issue seen any progress on getting resolved? We're still experiencing the bug even after updating everything. 

This seems to occur in Safari, Chrome, Firefox, and Internet Explorer 11.

We're running:
Craft 3.1.12
Redactor 2.3.1
On PHP 7.2.8

**Comment by andris-sevcenko** [comment]
@alandowling I'm still unable to reproduce this locally. Is it possible to get CP access to a site where you can reproduce this? If so, can you send it over to [support@craftcms.com](mailto:support@craftcms.com) and reference this ticket?

**Comment by carolineboeykens** [comment]
@andris-sevcenko, I sent an activation url to support@craftcms.com for a website we build where you can reproduce the issue.
