### ISSUE TITLE
Advanced Redactor settings seem to trigger "Leave Site?" warnings

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/redactor#161]
I just updated a Craft site and all its plugins to the recent versions. As soon as I started testing the site, I experienced "Leave Site?" warning messages when navigating away from any entry that had a populated redactor field.

It seems that any redactor field that has any of the following settings checked (see image) and has at least 2 formatting types (blockquote and h2 for example) will cause this warning message to pop up.

![Screen Shot 2019-08-30 at 3 31 29 PM](https://user-images.githubusercontent.com/1007191/64054664-fb884980-cb3c-11e9-9b74-e13fa1e65904.png)

**Comment by brandonkelly** [comment]
We just released Redactor 2.4.0 with a fix for this!

**Comment by jsunsawyer** [comment]
@brandonkelly I'm still experiencing this issue.

**Comment by NixonGit** [comment]
Can confirm we're also still seeing the issue, but the fix has alleviated the issue in some cases.

**Comment by jsunsawyer** [comment]
@brandonkelly Any chance we could re-open this issue? I'm still regularly experiencing this in Craft 3.3.10 / Redactor 2.4.0

**Comment by brandonkelly** [comment]
Can someone who is still experiencing this issue please send the following things to support@craftcms.com?

- a database backup
- your `config/redactor/` folder
- your `composer.json` and `composer.lock` files

**Comment by jsunsawyer** [comment]
@brandonkelly Sent

**Comment by brandonkelly** [comment]
Was able to reproduce when the field contained a void tag, where Redactor and HTML Purifier disagree on the syntax that should be used (`<hr>` vs `<hr />`). Also if there were any images, Redactor likes to add `data-image` attributes at random on initialization.

The self-closing tag syntax could have been prenormalized from PHP, but we can’t do anything to anticipate what those `data-image` attributes should be ahead of time. So I decided to just fix this from Craft’s end, by adding a little delay before storing the initial form values, giving Redactor a little more time to get its value normalized before it’s captured as the initial form value.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#602679ea534e23838ea03d3bb82552471ebc1d24 as 3.3.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jsunsawyer** [comment]
@brandonkelly I'm still getting this error pretty regularly.

I tested a simple entry with a single Redactor field. I added a 2nd paragraph, then saved. Upon deleting the 2nd paragraph, a `<br>` tag was left (which seems like its own issue).

This is what the Redactor content looks like when viewing through the "html" option.
```<p>Save $25 for every $500 you spend in store. Loyalty members also receive early access to exclusive offers, text message discounts, special product bundles, major event invitations, and new product announcements. Ask your Docent for more details.<br></p>```

So it seems like the `<br>` tag is still regularly causing issues in this case.

**Comment by brandonkelly** [comment]
@jsunsawyer And to be clear you definitely updated Craft to `602679ea534e23838ea03d3bb82552471ebc1d24` first per my last post? At that point it shouldn’t matter what Redactor does with its field value on initialization, as Craft won’t record its “initial” page value until after all other JS on load/doc-ready is finished executing.

**Comment by jsunsawyer** [comment]
@brandonkelly Ah, sorry. I just updated to the released version of 3.3.13. I assumed that this fix was included. Let me check it out.

**Comment by brandonkelly** [comment]
@stenvdb You’ll have to open an issue at https://github.com/wbrowar/craft-grid/issues about that.

**Comment by jsunsawyer** [comment]
@brandonkelly Updating to that version worked. Thanks!

**Comment by mattandrews** [comment]
Thanks for fixing this @brandonkelly!

**Comment by LorindaH** [comment]
I'm having this issue years later with version 3.0.4. Adding the text field doesn't make the "Leave Site" notice appear. If I add a link to the text (using the link button in the field's toolbar) then even if no edits are made the "Leave Site" notice appears when you leave the entry editor.
